### ISSUE TITLE
failure on os.login() does not allow user to proceed

### ISSUE THREAD

**Issue by adrianchang3** [adrianchang3/GDS_Scripts#6]
context: get_user() looks for username using os.login()

problem: if os.login() fails, there is no way for the user to proceed without a hard-code fix. 

preferred solution: implement py sg folderbrowse to allow user to set a directory.

**Comment by adrianchang3** [comment]
issue raised as a result of possible tkinter import failures on userend. Original exception handling was removed.

**Comment by cca32** [comment]
this issue might be resolved with #9 and https://github.com/adrianchang3/GDS_Scripts/pull/9/commits/7af0913e7ffa6615dabb788baf0c927dff5b5e51
we should close this issue whenever it gets tested with Rachel's computer
